name: Run Tests

on: [push, pull_request]

jobs:
  test-code:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/olfp/ga68-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and run repository sources
        run: make -B test
