name: Run Tests

on: [push, pull_request]

jobs:
  test-code:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/olfp/ga68-runner:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean build files
        run: make clean

      - name: Run test suite
        run: make test

      - name: Interaktive Debug-Sitzung starten (Nur für Sie zugänglich)
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true # BLOCKIERT den Zugriff für alle anderen GitHub-Nutzer
